### ISSUE TITLE
Statically compiled version

### ISSUE THREAD

**Issue by frenkiboy** [soedinglab/BaMMmotif#1]
Dear Anja, 

Is there a chance that you could provide a statically compiled version of the software, or at least a list of dependencies?

BeMMmotif looks extremely interesting, and I can't wait to try it out on my data!

Best regards, 

Vedran Franke

**Comment by AnjaSophieKiesel** [comment]
Dear Vedran,

thank you for your interest in our work!

A statically compiled version is now uploaded.  Within this week we will also provide the complete source code and better documentation. Additionally we would like to mention that the current version only works on sequences of equal length. 

In case of further questions, please don't hesitate to contact us.

Best regards,

Anja Kiesel

**Comment by AnjaSophieKiesel** [comment]
Dear Vedran!

FYI: the complete source code of BaMM!motif is now online, which includes a better help and documentation, as well as R scripts for plotting BaMM logos.

Best regards,
Anja
